name: CI/CD for Node.js App

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use an Ubuntu environment

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Path to the Dockerfile
          push: true
          tags: amana0/nodejs-container-app:latest


